## Знакомство с библиотеками для анализа данных. NumPy

Результат лабораторной работы − отчет в формате ноутбука Jupyter (ipynb-файл). Постарайтесь сделать ваш отчет интересным рассказом, последовательно отвечающим на вопросы из заданий. Помимо ответов на вопросы, в отчете так же должен быть код, однако чем меньше кода, тем лучше всем: нам − меньше проверять, вам —  проще найти ошибку или дополнить эксперимент. При проверке оценивается четкость ответов на вопросы, аккуратность отчета и кода.

### О задании

Лабораторные работы "NumPy" и "Pandas" направлены на работу с пакетами NumPy, Pandas и Matplotlib путём решения набора задач (да, алгебры и геометрии тут почти нет). В данных заданиях разрешено пользоваться только стандартной библиотекой языка Python, а также пакетами NumPy, Pandas и Matplotlib. Целью заданий является редактирование данного jupyter notebook-a (в части блоков с кодом на python) таким образом, чтобы были реализованы указанные в заданиях функции.


### Оценивание и штрафы

* Каждая из задач имеет определенную «стоимость» (указана в скобках около задачи)
* «Похожие» решения считаются плагиатом и все задействованные студенты (в том числе те, у кого списали) не могут получить за него больше 0 баллов
* Если вы нашли решение какого-то из заданий в открытом источнике, необходимо добавить ссылку на этот источник (скорее всего вы будете не единственным, кто это нашел, поэтому чтобы исключить подозрение в плагиате, необходима ссылка на источник)
* Не оцениваются задания с удалёнными формулировками
* Не оценивается лабораторная работа целиком, если она была выложена в открытый источник

###  Правила сдачи

Работу необходимо сдавать, загрузив в свой приватный репозиторий и сообщив об этом в телеграм @xrzvs (или просто открыв доступ к ноутбуку в Google Colab; более подробную информацию смотрите в README.md). 

### Знакомство с Numpy

Во всех заданиях данного ноутбука **запрещено** использовать циклы (ключевые слова *for* и *while*), [list comprehension](https://habrahabr.ru/post/30232/), [map и т.п.](http://pythonicway.com/python-functinal-programming)

Для каждой задачи приведите примеры использования реализованных функций. Без примеров баллы за задание будут снижены в 2 раза, примеры должны отличаться от тех что приведены в самом задании

Под матрицей в заданиях понимается двумерный [numpy.array](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html)

In [2]:
import numpy as np

**(0.25 балла) Задание 1.** Реализуйте функцию, принимающую на вход матрицу ```X``` и два массива индексов ```indices1``` и ```indices2``` одинаковой длины и возвращающую np.array, состоящий из последовательности элементов 

```[X[indices1[0], indices2[0]], ... , X[indices1[N-1], indices2[N-1]]]```

In [3]:
def construct_array(X, indices1, indices2):
    # Тута по интуиции, если совпало - так сошлись звезды
    return X[indices1, indices2]

assert np.allclose (construct_array(np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]), [1, 2, 3], [2, 1, 0]), np.array([6,8, 10]))

In [12]:
np.arange(18).reshape(3,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [9]:
construct_array(np.arange(18).reshape(3,6), [0,1,2], [1,2,2])

array([ 1,  8, 14])

**(0.25 балла) Задача 2.** Реализуйте функцию, которая на вход принимает два массива ```X``` и ```Y``` (массивы могут быть n-мерные, но их размерности должны совпадать), а возвращает **True** если они равны и **False** - иначе.

In [17]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
def detect_identic(X, Y):
    # Your code here
    return (X - Y == np.zeros(X.shape)).all()

assert np.allclose (detect_identic(np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]), np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 11]])), False)
assert np.allclose (detect_identic(np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]), np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])), True)

In [21]:
(np.arange(18).reshape(3,6) - np.arange(18).reshape(3,6) == np.zeros((3,6))).all()

True

**(0.25 балла) Задание 3.** Реализуйте функцию, которая на вход принимает цветное изображение ```X``` (трехмерный вектор размера (n, m, 3)) и возвращает среднее значение по трём каналам (вектор длины 3).

In [73]:
def mean_channel(X):
    # Your code here
    return np.array([X[:,:,0].reshape(-1).mean(), X[:,:,1].reshape(-1).mean(), X[:,:,2].reshape(-1).mean()])

assert np.allclose (mean_channel(np.arange(27).reshape((3, 3, 3))), np.array([12., 13., 14.]))

In [74]:
np.arange(60).reshape((4,5,3))[:,:,:]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[45, 46, 47],
        [48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]]])

**(0.25 балла) Задание 4.** Реализуйте функцию, принимающую на вход матрицу ```X``` и некоторое число ```a``` и возвращающую ближайший к числу элемент матрицы.

Например, для ```X = np.arange(0,10).reshape((2, 5))``` и ```a = 3.6``` ответом будет 4.

In [97]:
def nearest_value(X, a):
    # Your code here
    return X.ravel()[np.abs(X - np.full(X.shape,a)).argmin()]

assert np.allclose (nearest_value(np.arange(0,1000).reshape((10, 10, 10)), -1), 0)
assert np.allclose (nearest_value(np.arange(0,1000).reshape((10, 10, 10)), 160.5), 160)
assert np.allclose (nearest_value(np.arange(0,1000).reshape((10, 10, 10)), 160.6), 161)

In [113]:
a = 43

In [114]:
X = np.arange(10,110,10).reshape((2, 5))

In [115]:
X - np.full(X.shape,a)

array([[-33, -23, -13,  -3,   7],
       [ 17,  27,  37,  47,  57]])

In [116]:
np.abs(X - np.full(X.shape,a)).argmin()

3

In [117]:
nearest_value(X, a)

40

**(0.5 балла) Задача 5.** Реализуйте функцию, принимающую на вход два одномерных массива ```x``` и ```y``` и возвращающую матрицу, в которой первый массив соответствует первому столбцу матрицы, второй - второму.

В этом задании **запрещается** пользоваться операцией транспонирования и рекомедуется воспользоваться методом [reshape](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.reshape.html).

In [4]:
def construct_matrix(x, y):
    # Your code here
    return np.concatenate([x.reshape((1,x.shape[0],1)), y.reshape((1,y.shape[0],1))], axis=2)[0]

assert np.allclose (construct_matrix(np.arange(0, 6), np.arange(6, 12)), np.array([[0, 6], [1, 7], [2, 8], [3, 9], [4, 10], [5, 11]]))

In [157]:
x=np.array([1,3,3,7])
y=np.array([1,4,8,8])

In [162]:
x.reshape((1,x.shape[0],1))

array([[[1],
        [3],
        [3],
        [7]]])

In [159]:
np.concatenate([x.reshape((1,x.shape[0],1)), y.reshape((1,y.shape[0],1))], axis=2)[0]

array([[1, 1],
       [3, 4],
       [3, 8],
       [7, 8]])

In [160]:
construct_matrix(x,y)

array([[1, 1],
       [3, 4],
       [3, 8],
       [7, 8]])

**(0.5 балла) Задание 6.** Реализуйте функцию, которая на вход принимает вектор ```x```, содержащий целые числа, кроме 0, а возвращает вектор со вставленными нулями между числами.

Например, из ```[1, -5, 3]``` получить ```[1, 0, -5, 0, 3]```

In [190]:
def add_zeros(Z):
    # Your code here
    nz=1
    Z0 = np.zeros(len(Z) + (len(Z)-1))
    Z0[::nz+1] = Z
    return Z0
# https://pythonworld.ru/numpy/100-exercises.html
assert np.allclose (add_zeros(np.arange(1, 10)), np.array([1., 0., 2., 0., 3., 0., 4., 0., 5., 0., 6., 0., 7., 0., 8., 0., 9.]))
assert np.allclose (add_zeros(np.array([1])), np.array([1]))
assert np.allclose (add_zeros(np.array([])), np.array([]))

In [191]:
add_zeros(np.array([1,2,3,4]))

array([1., 0., 2., 0., 3., 0., 4.])

**(0.75 балла) Задание 7.** Реализуйте функцию для подсчёта произведения ненулевых элементов на диагонали прямоугольной матрицы

Например, для ```X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])``` ответом является 3. Если ненулевых элементов нет, функция должна возвращать ```None```.

In [216]:
def nonzero_product(X):
    # Your code here
    X=X.diagonal()
    X=X[X!=0].prod()
    if X==0:
        return None
    else:
        return X[X!=0].prod()

assert np.allclose (nonzero_product(np.array([[3, 3, 3], [5, 5, 5], [7, 7, 0]])), 15)
assert nonzero_product(np.array([[0, 3, 3], [5, 0, 5], [7, 7, 0]])) == None

In [222]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])

In [224]:
nonzero_product(X)

3

**(0.75 балла) Задание 8.** Реализуйте функцию, возвращающую максимальный элемент в массиве ```X``` среди элементов, перед которыми стоит нулевой.

Например, для ```X = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])``` ответом является 5. Если подходящих элементов нет, функция должна возвращать ```None```.

In [34]:
def max_element(X):
    # Your code here
    zidx = np.where(X == 0)[0]
    zidx += np.ones(zidx.shape[0]).astype(zidx.dtype)
    afterzeros = X[zidx[zidx < X.shape[0]]]
    afterzeros = afterzeros[afterzeros != 0]
    if afterzeros.shape[0] == 0:
        return None
    else:
        return afterzeros.max()


assert max_element(np.array([1,2,3,4,5])) == None
assert max_element(np.array([1,0,0,0,0])) == None
assert np.allclose(max_element(np.array([1,0,3,2,0])), 3)

In [35]:
X = np.array([1, 0, 0, 0, 0])

In [36]:
zidx = np.where(X == 0)[0]
zidx += np.ones(zidx.shape[0]).astype(zidx.dtype)
X[zidx[zidx < X.shape[0]]].max()
# zidx

0

**(0.75 балла) Задание 9.** Реализуйте функцию, принимающую на вход матрицу ```X``` и возвращающую все её уникальные строки в виде матрицы.

In [37]:
def get_unique_rows(X):
    # Your code here
    return np.unique(X, axis=0)


assert np.allclose (get_unique_rows(np.array([[1, 2], [1, 9], [1, 2],[1, 9]])), np.array([[1, 2], [1, 9]]))
assert np.allclose (get_unique_rows(np.zeros((10,10))), np.zeros(10))

**(0.75 балла) Задача 10.** Реализуйте функцию, которая во входной вещественной матрице ```X``` находит все значения ```nan``` и заменяет их на среднее арифметическое всех остальных элементов. Если все элементы матрицы ```nan```, то верните нулевую матрицу той же размерности.

In [73]:
def replace_nans(X):
    # Your code here
    mean = X[~np.isnan(X)].mean()
    if np.isnan(mean):
        return np.zeros(X.shape)
    X[np.isnan(X)] = mean
    return X


assert np.allclose (replace_nans(np.array([np.nan, np.nan])), np.zeros(2))
assert np.allclose (replace_nans(np.array([[2, np.nan], [np.nan, 3]])), np.array([[2., 2.5], [2.5, 3.]]))

<ipython-input-73-4bf42a9c8783>:3: RuntimeWarning: Mean of empty slice.
  mean = X[~np.isnan(X)].mean()


In [68]:
replace_nans(np.array([[2, np.nan], [np.nan, 3]]))

Mean: 2.5
Ret:  [[2.5 2.5]
 [2.5 2.5]]


array([[2.5, 2.5],
       [2.5, 2.5]])

In [312]:
X = np.array([[2, np.nan], [np.nan, 3]])

In [313]:
np.isnan(X)

array([[False,  True],
       [ True, False]])

In [326]:
X[X == 2] = 1337

In [327]:
X

array([[1.337e+03, 1.000e+00],
       [1.000e+00, 3.000e+00]])

In [61]:
arr[~np.isnan(arr)].mean()

<ipython-input-61-10b8f371ef2b>:1: RuntimeWarning: Mean of empty slice.
  arr[~np.isnan(arr)].mean()
/opt/anaconda3/anaconda3/lib/python3.8/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


nan

In [56]:
arr[np.isnan(arr)] = arr[~np.isnan(arr)].mean()

In [57]:
arr

array([[2. , 2.5],
       [2.5, 3. ]])

In [43]:
mask = np.isnan(arr)
idx = np.where(~mask,np.arange(mask.shape[1]),0)
np.maximum.accumulate(idx,axis=1, out=idx)
out = arr[np.arange(idx.shape[0])[:,None], idx]

IndexError: tuple index out of range

**(1 балл) Задача 11.** Напишите функцию, генерирующую [матрицу Вандермонда](https://ru.wikipedia.org/wiki/Определитель_Вандермонда), принимающую на вход вектор $(x_1, ... , x_n)$.

В этом задании **запрещается** пользоваться готовыми реализациями (например, [numpy.vander](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.vander.html)), а также [np.repeat](https://docs.scipy.org/doc/numpy/reference/generated/numpy.repeat.html) и [np.transpose](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html).

При решении задействуйте [np.reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html) и/или [np.newaxis](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html).

In [298]:
def vander(x):
    # Your code here
    y = np.arange(0,len(x))
    return (np.power(x[:,np.newaxis], y[np.newaxis,:]))

assert np.allclose (np.vander(np.array([]), increasing=True), vander(np.array([])))
assert np.allclose (np.vander(np.array([1, 2, 3, 5]), increasing=True), vander(np.array([1, 2, 3, 5])))

In [299]:
np.vander(np.array([1, 2, 3, 5]), increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

In [300]:
x=np.array([1, 2, 3, 5])

In [301]:
y = np.arange(0,len(x))

In [302]:
y

array([0, 1, 2, 3])

In [303]:
(np.power(x[:,np.newaxis], y[np.newaxis,:]))

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

**(1 балл) Задача 12.** Даны две вещественные матрицы ```X``` и ```Y``` с одинаковым числом столбцов и, в общем случае, различным числом строк. Необходимо реализовать функцию, вычисляющую матрицу попарных [косинусных коэффициентов](https://en.wikipedia.org/wiki/Cosine_similarity) между всеми $X_i$ и $Y_j$, где $X_i$ - $i$-ая строка матрицы $X$, а $Y_j$ - $j$-ая строка матрицы $Y$. 

В этом задании **запрещается** пользоваться готовыми реализациями, а также [np.repeat](https://docs.scipy.org/doc/numpy/reference/generated/numpy.repeat.html) и [np.transpose](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html).

При решении задействуйте [np.reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html) и/или [np.newaxis](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html), [np.sqrt](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sqrt.html), [np.sum](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html) и [np.power](https://docs.scipy.org/doc/numpy/reference/generated/numpy.power.html).

In [286]:
def count_cosine_similarity(X, Y):
    # Your code here
    x=np.sqrt(np.sum(np.power(X[:], 2), axis=1)) # модули векторов Х
    y=np.sqrt(np.sum(np.power(Y[:], 2), axis=1)) # модули векторов Y
    return np.tensordot(X[:],Y[:], axes=(1,1)) / (x[:,np.newaxis] * y[np.newaxis,:]) # произведения модулей векторов X_i, Y_i
    


assert np.allclose (count_cosine_similarity(np.array([[1, 2], [4, 8], [1, 2]]), np.array([[1, 2], [4, 2]])), np.array([[1, 0.8], [1, 0.8], [1, 0.8]]))
assert np.allclose (count_cosine_similarity(np.ones((10, 5)), np.ones((3, 5))), np.ones((10, 3)))

# Идея с tensordot отсюда https://stackoverflow.com/questions/36030963/dot-product-along-third-axis
# Идея с подсчетом матрицы произведений модулей отсюда https://scicomp.stackexchange.com/questions/10748/cartesian-products-in-numpy

In [331]:
X,Y=np.array([[1, 2], [4, 8], [1, 2]]),  np.array([[1, 2], [4, 2]])

In [332]:
X

array([[1, 2],
       [4, 8],
       [1, 2]])

In [333]:
Y

array([[1, 2],
       [4, 2]])

In [334]:
x=np.sqrt(np.sum(np.power(X[:], 2), axis=1)) # модули векторов Х

In [335]:
x

array([2.23606798, 8.94427191, 2.23606798])

In [336]:
X[:]

array([[1, 2],
       [4, 8],
       [1, 2]])

In [337]:
np.power(X[:], 2)

array([[ 1,  4],
       [16, 64],
       [ 1,  4]])

In [339]:
np.sqrt(np.sum(np.power(X[:], 2), axis=1))

array([2.23606798, 8.94427191, 2.23606798])

In [340]:
y=np.sqrt(np.sum(np.power(Y[:], 2), axis=1)) # модули векторов Y

In [341]:
x,y

(array([2.23606798, 8.94427191, 2.23606798]), array([2.23606798, 4.47213595]))

In [342]:
x[:,np.newaxis] * y[np.newaxis,:]

array([[ 5., 10.],
       [20., 40.],
       [ 5., 10.]])

In [263]:
np.tile(x, len(y))

array([2.23606798, 8.94427191, 2.23606798, 2.23606798, 8.94427191,
       2.23606798])

In [264]:
np.repeat(y, len(x))

array([2.23606798, 2.23606798, 2.23606798, 4.47213595, 4.47213595,
       4.47213595])

In [265]:
np.tile(x, len(y)) * np.repeat(y, len(x))

array([ 5., 20.,  5., 10., 40., 10.])

In [266]:
(np.tile(y, len(x)) * np.repeat(x, len(y))).reshape(len(x),len(y)) # произведения модулей векторов X_i, Y_i

array([[ 5., 10.],
       [20., 40.],
       [ 5., 10.]])

In [268]:
np.sum(np.power(X[:], 2), axis=1)*np.sum(np.power(Y[[0]], 2), axis=1)

array([ 25, 400,  25])

In [269]:
construct_matrix(Y[0],Y[1])

array([[1, 4],
       [2, 2]])

In [270]:
np.dot(X[:], Y[1])

array([ 8, 32,  8])

In [271]:
X[:].dot(Y[1])

array([ 8, 32,  8])

In [272]:
(np.tile(y, len(x)) * np.repeat(x, len(y)))

array([ 5., 10., 20., 40.,  5., 10.])

In [273]:
X[:]

array([[1, 2],
       [4, 8],
       [1, 2]])

In [274]:
Y[:]

array([[1, 2],
       [4, 2]])

In [275]:
np.matmul(X[:], Y[1])

array([ 8, 32,  8])

In [276]:
np.tensordot(X[:],Y[:], axes=(1,1))

array([[ 5,  8],
       [20, 32],
       [ 5,  8]])

In [277]:
np.tensordot(X[:],Y[:], axes=(1,1)) / (np.tile(y, len(x)) * np.repeat(x, len(y))).reshape(len(x),len(y)) # произведения модулей векторов X_i, Y_i

array([[1. , 0.8],
       [1. , 0.8],
       [1. , 0.8]])

In [278]:
np.linalg.norm(X[[0,1]])

9.219544457292887

In [279]:
X[0].dot(Y[0])

5

In [280]:
np.linalg.norm(X[0])

2.23606797749979

In [281]:
X[0].dot(Y[0])/(np.linalg.norm(X[0]) * np.linalg.norm(Y[0]))

0.9999999999999998

In [282]:
np.linalg.norm(np.array([1,2]))

2.23606797749979