# Задание по лекциям 1.

- Не нужно использовать эффективные вычислительные алгоритмы. Нужно использовать те алгоритмы, что были представлены на лекции или практических занятиях. 
- Остальное как обычно: за "похожие" решения всем задействованным 0 баллов; если используете решение из открытого источника — обязательно вставьте ссылку; не удаляйте формулировки; не выкладывайте в открытый источник.
- Можно использовать `numpy.array` для матриц и матричной арифметики и `numpy.linalg` для подсчёта ранга и определителя, для вычисления обратной матрицы, решения СЛУ и т.п. То есть то, что вы уже реализовывали в прошлом семестре, ещё раз реализовывать необязательно. Более того, можно использовать в любом из *заданий по лекциям* функции, реализованные ранее в других *заданиях по лекциям*. Если возникнут сомнения, можно ли использовать ту или иную функцию — лучше сразу поинтересуйтесь у меня.

$\mathbb{R}^n$ — вещественнозначное пространство вектор-**столбцов**.

In [1]:
import numpy as np
import scipy.optimize
import scipy.linalg

In [2]:
# https://stackoverflow.com/questions/15638650/is-there-a-standard-solution-for-gauss-elimination-in-python
def gauss(A):
    pl, u = scipy.linalg.lu(A, permute_l=True)
    return scipy.optimize._remove_redundancy._remove_redundancy(u, np.zeros_like(u[:, 0]))[0]

In [3]:
gauss(np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[1,4,1,0]]))

array([[1., 0., 0., 0.],
       [0., 4., 1., 0.],
       [0., 0., 1., 0.]])

In [21]:
gauss(np.array([[2,0,1,-3],[1,0,3,-4],[-1,0,2,-1],[1,0,1,-2]]).T)

array([[-3.        , -4.        , -1.        , -2.        ],
       [ 0.        ,  1.66666667,  1.66666667,  0.33333333]])

In [4]:
def make_good(v):
    for i,e in enumerate(v):
        if abs(e) > 1e-10:
            return v / e

def fsr(A):
    bad_fsr = scipy.linalg.null_space(A)
    new_fsr = []
    for i in range(len(bad_fsr[0])):
        new_fsr.append(make_good(bad_fsr[:,i]))
    return np.array(new_fsr)

In [5]:
ok = fsr(np.array([[1,1,1],[1,1,1],[1,1,1]]))

In [6]:
ok

array([[ 1. , -0.5, -0.5],
       [-0. ,  1. , -1. ]])

**(1 балл) Задание 1.** Реализовать функцию, принимающую на вход два набора 
$$
u = (u_1, \ldots, u_n),\ v = (v_1,\ldots,v_n)
$$
координат векторов (в стандартном базисе) из пространства $\mathbb{R}^n$, и выдающую 
- матрицу перехода от базиса $u$ к базису $v$, если оба этих набора являются базисами;
- None, иначе (альтернативный вариант — кидать исключение).

In [7]:
def m_perex(U, V):
    if len(gauss(U)) < len(U) or len(gauss(L)) < len(L):
        return None
    try:
        T_tr = []
        for vec in V:
            T_tr.append(np.linalg.solve(U.T, vec))
        return np.array(T_tr).T
    except Exception as e:
        return None

In [8]:
U = np.array([[1,2],[3,5]])
L = np.array([[-1,3], [4,6]])
m_perex(U,L)

array([[14., -2.],
       [-5.,  2.]])

**(1 балл) Задание 2.** Реализовать функцию, принимающую на вход матрицу $A$ линейного оператора $\varphi: \mathbb{R}^n \to \mathbb{R}^n$ (в стандартном базисе) и набор координат $u = (u_1,\ldots,u_n)$ вектор-столбцов, и выдающую 
- матрицу оператора $\varphi$ в базисе $u$, если $u$ является базисом;
- None, иначе (альтернативный вариант — кидать исключение).

In [9]:
def phi_in_strange_basis(phi, U):
    E = np.eye(len(phi))
    if len(gauss(U)) < len(U):
        return None
    Teu = m_perex(E, U)
    print(Teu)
    return np.linalg.inv(Teu).dot(phi).dot(Teu)

**(1.5 балла) Задание 3.** Реализовать функции, которые по данной матрице $A$ линейного оператора $\varphi: \mathbb{R}^n \to \mathbb{R}^n$ в стандартном базисе, выдадут:

- базис образа $\varphi$ (0.5 балла)
- базис ядра $\varphi$ (0.75 балла)
- размерности ядра и образа $\varphi$ (0.25 балла)

In [10]:
def phi_basis(A):
    return gauss(A.T)

def ker(A):
    return fsr(A)

def phi_basis_rank(A):
    return len(phi_basis(A))

def ker_rank(A):
    return len(ker(A))

In [18]:
a = np.array([
    [2,0,1,-3],
    [1,0,3,-4],
    [-1,0,2,-1],
    [1,0,1,-2]
    ])
ker(a)

array([[ 1.        , -0.94575653,  1.        ,  1.        ],
       [ 1.        ,  3.17206374,  1.        ,  1.        ]])

In [20]:
phi_basis(np.array([
    [2,0,1,-3],
    [1,0,3,-4],
    [-1,0,2,-1],
    [1,0,1,-2]
]))

array([[-3.        , -4.        , -1.        , -2.        ],
       [ 0.        ,  1.66666667,  1.66666667,  0.33333333]])

**(1 балл) Задание 4.** Реализовать функцию, принимающую на вход матрицу $A$ линейного оператора $\varphi: \mathbb{R}^n \to \mathbb{R}^n$ (в стандартном базисе) и набор координат $u = (u_1,\ldots,u_k),\ k\le n$ вектор-столбцов, и выдающую 
- True, если линейная оболочка векторов $(u_1,\ldots, u_k)$ является $\varphi$-инвариантным подпространством.
- False, иначе.

In [13]:
def is_phi_invariant(U, phi):
    """
    U - массив векторов (строки - вектора)
    phi - матрица преобразования (строки - строки)
    """
    U = gauss(U)
    tmp = phi.dot(U.T).T # строки - вектора вида Au_i (phi(u_i))
    tmp = gauss(np.concatenate([U, tmp]))
    print(tmp)
    return tmp.shape[0] == U.shape[0]

In [17]:
A = np.array([[1, 0, 0],
[0, 0, 0],
[0, 0, 0]])

U = np.array([[1, 2, 1],
[2, 4, 0],
[3, 6, 0]]).T

# A = np.array([[1, 0, 0],
# [1, 0, 0],
# [1, 0, 0]])

# U = np.array([[1, 1],
# [0, 2],
# [0, 3]]).T

is_phi_invariant(U, A)

[[ 2.  4.  6.]
 [ 0. -4. -6.]]


True